### ISSUE TITLE
Release 1.13.0

### ISSUE THREAD

**Issue by grantland** [ParsePlatform/Parse-SDK-Android#340]
https://github.com/ParsePlatform/Parse-SDK-Android/milestones/1.13.0

- [X] New: Add configurable serverURL to Parse.Configuration #330
- [X] Fix: Default parse server url #356
- [X] Fix: Avoid add unnecessary ParseDecompressInterceptor #358
- [X] Fix: Remove Content-Encoding header when we auto unzip the response stream #359
